hand_tracker:
    width: 0.2
    height: 0.4
    depth: 0.6
    heightOffset: 0.3
    depthOffset: 0.3

hand_controller:
    SpeedParameter: 3.0
    angularParameter: 3.0
    Xtarget: 0.6
    Ytarget: 0.0
